POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/operador/src/yocto-rasp/poky/meta \
  /home/operador/src/yocto-rasp/poky/meta-poky \
  /home/operador/src/yocto-rasp/poky/meta-yocto-bsp \
  /home/operador/src/yocto-rasp/meta-openembedded/meta-oe \
  /home/operador/src/yocto-rasp/meta-openembedded/meta-python \
  /home/operador/src/yocto-rasp/meta-openembedded/meta-networking \
  /home/operador/src/yocto-rasp/meta-openembedded/meta-webserver \
  /home/operador/src/yocto-rasp/meta-raspberrypi \
  "
