MACHINE ?= "qemux86-64"
#MACHINE ?= "raspberrypi0-wifi"
#MACHINE ?= "raspberrypi0-2w-64"

DL_DIR ?= "/media/operador/pseudonas/build/yocto/downloads"
SSTATE_DIR ?= "/media/operador/pseudonas/build/yocto/sstate-cache"
TMPDIR = "/media/operador/pseudonas/build/yocto/tmp-build-rasp"
#DEPLOY_DIR = "/media/operador/pseudonas/build/yocto/deploy"

# Distro config
DISTRO ?= "poky"
DISTRO_FEATURES:append = " systemd pam"
INIT_MANAGER ?= "systemd"
PACKAGE_CLASSES ?= "package_ipk"
SDKMACHINE ?= "x86_64"

EXTRA_IMAGE_FEATURES ?= " debug-tweaks"
#EXTRA_IMAGE_FEATURES:remove ?= " debug-tweaks"
#EXTRA_IMAGE_FEATURES:append ?= " allow-root-login"

# Password:
# openssl passwd -1 "treinamento"
# Password string must be escaped: $1$rUoxx8Mm$Cuh4DVPUtvkhG4oeWPtg/0
INHERIT+= " extrausers"
PASSWD = "\$1\$rUoxx8Mm\$Cuh4DVPUtvkhG4oeWPtg/0"
EXTRA_USERS_PARAMS += "useradd -m -p '${PASSWD}' embarcados"

#EXTRA_USERS_PARAMS = "usermod -p treinamento root;"

USER_CLASSES ?= "buildstats"

# Runtime testing of images
#IMAGE_CLASSES += "testimage testsdk"
#TESTIMAGE_AUTO:qemuall = "1"

BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"

PACKAGECONFIG:append:pn-qemu-system-native = " sdl"

# IMAGE_FSTYPES = "rpi-sdimg"
ENABLE_UART = "1"
ENABLE_SPI_BUS = "1"
ENABLE_I2C = "1"
IMAGE_OVERHEAD_FACTOR = "1.8"

IMAGE_INSTALL:append = " python3 python3-venv python3-pip"

INHERIT+="toaster buildhistory"

HOSTNAME = "treinamento"
#BB_NO_NETWORK = "1"

# https://github.com/RPi-Distro/firmware-nonfree/issues/29
# https://meta-raspberrypi.readthedocs.io/en/latest/ipcompliance.html#linux-firmware-rpidistro
# IP Compliance
# linux-firmware-rpidistro
#LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

BB_HASHSERVE = "auto"
BB_SIGNATURE_HANDLER = "OEEquivHash"
BB_SERVER_TIMEOUT = "600"
CONF_VERSION = "2"

# Build optimization
PARALLEL_MAKE = "-j 2"
BB_NUMBER_THREADS = "2"
BB_NUMBER_PARSE_THREADS = "4"
XZ_DEFAULTS = "--memlimit=1024MiB"
#XZ_DEFAULTS = "--memlimit=2048MiB"
INHERIT += "rm_work"

# Instrui utilizacao de ccache
INHERIT += "ccache"
CCACHE_DIR = "/home/operador/.ccache"
